services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8181:8000"
    environment:
      - API_KEY=${API_KEY}
      - TZ=America/Los_Angeles
      - PREFECT_API_URL=http://${HOST}:4200/api
    volumes:
      - ./static:/app/static
      - ./gtfs_data:/app/gtfs_data
      - ./data:/app/data  # Mount data directory for SQLite database
    restart: always

  prefect:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
      - ./src:/app/src
      - ./data:/app/data  # Mount data directory for SQLite database
    environment:
      - PREFECT_UI_URL=http://${HOST}:4200/api
      - PREFECT_API_URL=http://${HOST}:4200/api
    restart: always

volumes:
  prefect_data:
