version: '3'

services:
  caltrain-dashboard:
    build: .
    ports:
      - "8050:8050"
    environment:
      - API_KEY=${API_KEY}
      - TZ=America/Los_Angeles
    volumes:
      - ./data:/data
      - ./gtfs_data:/data/gtfs_data
      - ./docs:/docs
    restart: always
