"""
Script to create a complete working on-time heatmap notebook.
Run this to regenerate the notebook with the full data processing pipeline.
"""
import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Caltrain On-Time Performance Heatmap (2025)\n",
                "\n",
                "This notebook visualizes the on-time percentage for each day of 2025 using a calendar heatmap.\n",
                "Each square represents a day, colored by the on-time percentage for that day.\n",
                "\n",
                "Data is loaded directly from the database and processed to calculate delays."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "import sqlite3\n",
                "import pandas as pd\n",
                "import numpy as np\n",
                "import plotly.graph_objects as go\n",
                "from datetime import datetime, timedelta\n",
                "\n",
                "# Add project root to path for imports\n",
                "project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))\n",
                "sys.path.insert(0, project_root)\n",
                "\n",
                "# Database path\n",
                "DB_PATH = os.path.join(project_root, 'data', 'caltrain_lat_long.db')\n",
                "print(f\"Database path: {DB_PATH}\")\n",
                "print(f\"Database exists: {os.path.exists(DB_PATH)}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Load and Process Data\n",
                "\n",
                "We'll load raw data from the database and process it to calculate delays.\n",
                "This logic is repurposed from `data_processing.py`."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import utility functions from the project\n",
                "sys.path.insert(0, os.path.join(project_root, 'src'))\n",
                "from utils.time_utils import calculate_time_difference, normalize_time\n",
                "from utils.geo_utils import haversine\n",
                "\n",
                "def load_raw_train_data(year=2025):\n",
                "    \"\"\"Load raw train location data from the database for a specific year.\"\"\"\n",
                "    conn = sqlite3.connect(DB_PATH)\n",
                "    \n",
                "    query = f\"\"\"\n",
                "    SELECT \n",
                "        trip_id,\n",
                "        stop_id,\n",
                "        vehicle_lat,\n",
                "        vehicle_lon,\n",
                "        timestamp\n",
                "    FROM train_locations\n",
                "    WHERE timestamp LIKE '{year}%'\n",
                "    \"\"\"\n",
                "    \n",
                "    try:\n",
                "        df = pd.read_sql_query(query, conn)\n",
                "        print(f\"Loaded {len(df):,} raw records from database for {year}\")\n",
                "        \n",
                "        if not df.empty:\n",
                "            df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')\n",
                "            df = df.dropna(subset=['timestamp'])\n",
                "            print(f\"Date range: {df['timestamp'].min()} to {df['timestamp'].max()}\")\n",
                "        \n",
                "        return df\n",
                "    finally:\n",
                "        conn.close()\n",
                "\n",
                "def load_gtfs_data():\n",
                "    \"\"\"Load GTFS static data (stops and stop times).\"\"\"\n",
                "    gtfs_path = os.path.join(project_root, 'gtfs_data')\n",
                "    \n",
                "    stops_df = pd.read_csv(os.path.join(gtfs_path, 'stops.txt'))\n",
                "    stops_df = stops_df[stops_df['stop_id'].str.isnumeric()]\n",
                "    \n",
                "    stop_times_df = pd.read_csv(os.path.join(gtfs_path, 'stop_times.txt'))\n",
                "    \n",
                "    print(f\"Loaded {len(stops_df)} stops and {len(stop_times_df):,} stop times from GTFS\")\n",
                "    return stops_df, stop_times_df\n",
                "\n",
                "def process_arrival_data(raw_df, stops_df, stop_times_df):\n",
                "    \"\"\"Process raw train data to calculate delays (repurposed from data_processing.py).\"\"\"\n",
                "    if raw_df.empty or stops_df.empty or stop_times_df.empty:\n",
                "        print(\"WARNING: One or more input DataFrames are empty\")\n",
                "        return pd.DataFrame()\n",
                "    \n",
                "    print(\"Processing arrival data...\")\n",
                "    \n",
                "    # Ensure consistent data types - convert to string first, then to int\n",
                "    # This handles cases where trip_id might be stored as text in database\n",
                "    raw_df = raw_df.copy()\n",
                "    raw_df['stop_id'] = pd.to_numeric(raw_df['stop_id'].astype(str), errors='coerce').astype('Int64')\n",
                "    raw_df['trip_id'] = pd.to_numeric(raw_df['trip_id'].astype(str), errors='coerce').astype('Int64')\n",
                "    \n",
                "    stops_df = stops_df.copy()\n",
                "    stops_df['stop_id'] = pd.to_numeric(stops_df['stop_id'].astype(str), errors='coerce').astype('Int64')\n",
                "    \n",
                "    stop_times_df = stop_times_df.copy()\n",
                "    stop_times_df['stop_id'] = pd.to_numeric(stop_times_df['stop_id'].astype(str), errors='coerce').astype('Int64')\n",
                "    stop_times_df['trip_id'] = pd.to_numeric(stop_times_df['trip_id'].astype(str), errors='coerce').astype('Int64')\n",
                "    \n",
                "    # Drop rows with NaN in key columns\n",
                "    raw_df = raw_df.dropna(subset=['trip_id', 'stop_id'])\n",
                "    print(f\"After type conversion: {len(raw_df):,} records\")\n",
                "    \n",
                "    # Merge datasets\n",
                "    df2 = pd.merge(raw_df, stop_times_df[['trip_id', 'stop_id', 'arrival_time']], \n",
                "                   on=['trip_id', 'stop_id'], how='inner')\n",
                "    df2 = pd.merge(df2, stops_df[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']], \n",
                "                   on=['stop_id'], how='inner')\n",
                "    \n",
                "    print(f\"Merged data: {len(df2):,} records\")\n",
                "    \n",
                "    # Calculate distance between train and stop\n",
                "    df2['distance'] = df2.apply(lambda row: haversine(\n",
                "        row['vehicle_lat'], row['vehicle_lon'], row['stop_lat'], row['stop_lon']\n",
                "    ), axis=1)\n",
                "    \n",
                "    df2['date'] = df2['timestamp'].dt.date\n",
                "    df2['arrival_time'] = df2['arrival_time'].apply(normalize_time)\n",
                "    \n",
                "    # Find minimum distance for each trip-stop-date\n",
                "    min_distances = df2.groupby(['trip_id', 'stop_id', 'date'])['distance'].min().reset_index()\n",
                "    merged_df = pd.merge(df2, min_distances, on=['trip_id', 'stop_id', 'date', 'distance'])\n",
                "    \n",
                "    # Get closest approach time\n",
                "    arrival_times = merged_df.groupby(['trip_id', 'stop_id', 'date']).first().reset_index()\n",
                "    arrival_times = arrival_times[['trip_id', 'stop_id', 'date', 'timestamp', 'arrival_time', 'stop_name']]\n",
                "    arrival_times.rename(columns={'timestamp': 'actual_arrival_time'}, inplace=True)\n",
                "    \n",
                "    print(f\"Calculated {len(arrival_times):,} arrival events\")\n",
                "    \n",
                "    # Calculate delay\n",
                "    arrival_times['delay_minutes'] = arrival_times.apply(\n",
                "        lambda row: calculate_time_difference(row['arrival_time'], row['actual_arrival_time']), \n",
                "        axis=1\n",
                "    )\n",
                "    \n",
                "    # Clean unrealistic delays\n",
                "    arrival_times.loc[arrival_times.delay_minutes > 500, 'delay_minutes'] = 0.0\n",
                "    arrival_times.loc[arrival_times.delay_minutes < -100, 'delay_minutes'] = 0.0\n",
                "    \n",
                "    # Determine severity\n",
                "    arrival_times['delay_severity'] = 'On Time'\n",
                "    arrival_times.loc[(arrival_times.delay_minutes > 4) & (arrival_times.delay_minutes <= 15), 'delay_severity'] = 'Minor'\n",
                "    arrival_times.loc[arrival_times.delay_minutes > 15, 'delay_severity'] = 'Major'\n",
                "    arrival_times.loc[arrival_times.delay_minutes < 0, 'delay_minutes'] = 0\n",
                "    \n",
                "    print(f\"Processing complete!\")\n",
                "    return arrival_times\n",
                "\n",
                "# Load and process data\n",
                "print(\"Loading raw train data...\")\n",
                "raw_df = load_raw_train_data(year=2025)\n",
                "\n",
                "print(\"\\nLoading GTFS schedule data...\")\n",
                "stops_df, stop_times_df = load_gtfs_data()\n",
                "\n",
                "print(\"\\nProcessing arrivals and calculating delays...\")\n",
                "df = process_arrival_data(raw_df, stops_df, stop_times_df)\n",
                "\n",
                "print(f\"\\nFinal: {len(df):,} arrival events with delay data\")\n",
                "print(f\"\\nDelay severity counts:\")\n",
                "print(df['delay_severity'].value_counts())\n",
                "df.head()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Calculate Daily Statistics"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def calculate_daily_on_time_percentage(df):\n",
                "    \"\"\"Calculate on-time percentage for each day.\"\"\"\n",
                "    if df.empty:\n",
                "        return pd.DataFrame()\n",
                "    \n",
                "    # Calculate percentage on-time per day\n",
                "    daily_summary = df.groupby('date')['delay_severity'].apply(\n",
                "        lambda x: (x == 'On Time').mean() * 100\n",
                "    ).reset_index()\n",
                "    daily_summary.columns = ['date', 'on_time_pct']\n",
                "    \n",
                "    # Get counts\n",
                "    daily_counts = df.groupby('date').size().reset_index(name='count')\n",
                "    daily_summary = daily_summary.merge(daily_counts, on='date')\n",
                "    daily_summary['date'] = pd.to_datetime(daily_summary['date'])\n",
                "    \n",
                "    print(f\"Calculated stats for {len(daily_summary)} days\")\n",
                "    print(f\"Average on-time: {daily_summary['on_time_pct'].mean():.1f}%\")\n",
                "    \n",
                "    return daily_summary\n",
                "\n",
                "daily_stats = calculate_daily_on_time_percentage(df)\n",
                "daily_stats.head(10)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Create Calendar Heatmap"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def prepare_calendar_data(daily_stats, year=2025):\n",
                "    \"\"\"Prepare data for calendar heatmap.\"\"\"\n",
                "    start_date = pd.Timestamp(f'{year}-01-01')\n",
                "    end_date = pd.Timestamp(f'{year}-12-31')\n",
                "    all_dates = pd.date_range(start=start_date, end=end_date, freq='D')\n",
                "    \n",
                "    complete_df = pd.DataFrame({'date': all_dates})\n",
                "    \n",
                "    if not daily_stats.empty:\n",
                "        daily_stats = daily_stats.copy()\n",
                "        daily_stats['date'] = pd.to_datetime(daily_stats['date'])\n",
                "        complete_df = complete_df.merge(daily_stats, on='date', how='left')\n",
                "    else:\n",
                "        complete_df['on_time_pct'] = np.nan\n",
                "        complete_df['count'] = 0\n",
                "    \n",
                "    complete_df['day_of_week'] = complete_df['date'].dt.dayofweek\n",
                "    first_day = complete_df['date'].iloc[0]\n",
                "    complete_df['week_id'] = ((complete_df['date'] - first_day).dt.days + first_day.dayofweek) // 7\n",
                "    \n",
                "    return complete_df\n",
                "\n",
                "calendar_data = prepare_calendar_data(daily_stats, year=2025)\n",
                "print(f\"Calendar: {len(calendar_data)} days total\")\n",
                "print(f\"Days with data: {calendar_data['on_time_pct'].notna().sum()}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def create_calendar_heatmap(calendar_data, year=2025):\n",
                "    \"\"\"Create GitHub-style calendar heatmap.\"\"\"\n",
                "    if calendar_data is None or calendar_data.empty:\n",
                "        print(\"No data available\")\n",
                "        return None\n",
                "    \n",
                "    num_weeks = calendar_data['week_id'].max() + 1\n",
                "    heatmap_values = np.full((7, num_weeks), np.nan)\n",
                "    hover_texts = [['' for _ in range(num_weeks)] for _ in range(7)]\n",
                "    \n",
                "    for _, row in calendar_data.iterrows():\n",
                "        week_idx = int(row['week_id'])\n",
                "        day_idx = int(row['day_of_week'])\n",
                "        \n",
                "        if pd.notna(row['on_time_pct']):\n",
                "            heatmap_values[day_idx, week_idx] = row['on_time_pct']\n",
                "            hover_texts[day_idx][week_idx] = (\n",
                "                f\"<b>{row['date'].strftime('%A, %b %d, %Y')}</b><br>\"\n",
                "                f\"On-Time: <b>{row['on_time_pct']:.1f}%</b><br>\"\n",
                "                f\"Arrivals: {int(row['count']) if pd.notna(row['count']) else 0}\"\n",
                "            )\n",
                "        else:\n",
                "            heatmap_values[day_idx, week_idx] = -1\n",
                "            hover_texts[day_idx][week_idx] = f\"<b>{row['date'].strftime('%A, %b %d, %Y')}</b><br>No data\"\n",
                "    \n",
                "    day_labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']\n",
                "    \n",
                "    # Month labels\n",
                "    month_positions = []\n",
                "    month_labels = []\n",
                "    current_month = None\n",
                "    \n",
                "    for _, row in calendar_data.iterrows():\n",
                "        month = row['date'].strftime('%b')\n",
                "        if month != current_month:\n",
                "            month_positions.append(row['week_id'])\n",
                "            month_labels.append(month)\n",
                "            current_month = month\n",
                "    \n",
                "    colorscale = [\n",
                "        [0.0, '#161b22'],\n",
                "        [0.01, '#161b22'],\n",
                "        [0.02, '#da3633'],\n",
                "        [0.25, '#f85149'],\n",
                "        [0.50, '#d29922'],\n",
                "        [0.75, '#3fb950'],\n",
                "        [1.0, '#238636']\n",
                "    ]\n",
                "    \n",
                "    fig = go.Figure(data=go.Heatmap(\n",
                "        z=heatmap_values,\n",
                "        x=list(range(num_weeks)),\n",
                "        y=day_labels,\n",
                "        text=hover_texts,\n",
                "        hoverinfo='text',\n",
                "        colorscale=colorscale,\n",
                "        zmin=-1,\n",
                "        zmax=100,\n",
                "        colorbar=dict(\n",
                "            title=dict(text='On-Time %', font=dict(color='#c9d1d9')),\n",
                "            thickness=15,\n",
                "            len=0.6,\n",
                "            ticksuffix='%',\n",
                "            tickvals=[0, 25, 50, 75, 100],\n",
                "            tickfont=dict(color='#c9d1d9'),\n",
                "        ),\n",
                "        xgap=3,\n",
                "        ygap=3,\n",
                "    ))\n",
                "    \n",
                "    valid_data = calendar_data[calendar_data['on_time_pct'].notna()]\n",
                "    if not valid_data.empty:\n",
                "        avg_on_time = valid_data['on_time_pct'].mean()\n",
                "        total_arrivals = valid_data['count'].sum()\n",
                "        days_tracked = len(valid_data)\n",
                "        subtitle = f\"Average: {avg_on_time:.1f}% on-time | {days_tracked} days | {int(total_arrivals):,} arrivals\"\n",
                "    else:\n",
                "        subtitle = \"No data\"\n",
                "    \n",
                "    fig.update_layout(\n",
                "        title=dict(\n",
                "            text=f'🚆 Caltrain On-Time Performance {year}<br><span style=\"font-size:14px;color:#8b949e\">{subtitle}</span>',\n",
                "            font=dict(size=24, color='#c9d1d9'),\n",
                "            x=0.5,\n",
                "            xanchor='center'\n",
                "        ),\n",
                "        xaxis=dict(\n",
                "            tickmode='array',\n",
                "            tickvals=month_positions,\n",
                "            ticktext=month_labels,\n",
                "            tickfont=dict(size=12, color='#8b949e'),\n",
                "            side='top',\n",
                "            showgrid=False,\n",
                "        ),\n",
                "        yaxis=dict(\n",
                "            tickfont=dict(size=11, color='#8b949e'),\n",
                "            showgrid=False,\n",
                "            autorange='reversed',\n",
                "        ),\n",
                "        plot_bgcolor='#0d1117',\n",
                "        paper_bgcolor='#0d1117',\n",
                "        height=280,\n",
                "        width=1100,\n",
                "        margin=dict(l=50, r=120, t=100, b=30),\n",
                "    )\n",
                "    \n",
                "    return fig\n",
                "\n",
                "fig = create_calendar_heatmap(calendar_data, year=2025)\n",
                "if fig:\n",
                "    fig.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Summary Statistics"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def display_summary_stats(daily_stats):\n",
                "    \"\"\"Display summary statistics.\"\"\"\n",
                "    if daily_stats.empty:\n",
                "        print(\"No data\")\n",
                "        return\n",
                "    \n",
                "    valid_stats = daily_stats[daily_stats['on_time_pct'].notna()]\n",
                "    \n",
                "    print(\"=\" * 60)\n",
                "    print(\"🚆 CALTRAIN ON-TIME PERFORMANCE - 2025\")\n",
                "    print(\"=\" * 60)\n",
                "    print(f\"\\n📅 Days with data: {len(valid_stats)}\")\n",
                "    print(f\"🚉 Total arrivals: {valid_stats['count'].sum():,}\")\n",
                "    print(f\"\\n📊 Overall on-time: {valid_stats['on_time_pct'].mean():.1f}%\")\n",
                "    \n",
                "    best_idx = valid_stats['on_time_pct'].idxmax()\n",
                "    worst_idx = valid_stats['on_time_pct'].idxmin()\n",
                "    \n",
                "    print(f\"\\n✅ Best: {valid_stats.loc[best_idx, 'date'].strftime('%b %d')} ({valid_stats['on_time_pct'].max():.1f}%)\")\n",
                "    print(f\"❌ Worst: {valid_stats.loc[worst_idx, 'date'].strftime('%b %d')} ({valid_stats['on_time_pct'].min():.1f}%)\")\n",
                "    \n",
                "    # Day of week\n",
                "    valid_stats = valid_stats.copy()\n",
                "    valid_stats['day_of_week'] = valid_stats['date'].dt.day_name()\n",
                "    dow_avg = valid_stats.groupby('day_of_week')['on_time_pct'].mean()\n",
                "    \n",
                "    day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']\n",
                "    dow_avg = dow_avg.reindex([d for d in day_order if d in dow_avg.index])\n",
                "    \n",
                "    print(\"\\n📆 By Day of Week:\")\n",
                "    print(\"-\" * 40)\n",
                "    for day, pct in dow_avg.items():\n",
                "        bar = \"█\" * int(pct // 5) + \"░\" * (20 - int(pct // 5))\n",
                "        emoji = \"🟢\" if pct >= 80 else \"🟡\" if pct >= 60 else \"🔴\"\n",
                "        print(f\"{emoji} {day:10} {pct:5.1f}% |{bar}|\")\n",
                "    \n",
                "    # Monthly\n",
                "    valid_stats['month'] = valid_stats['date'].dt.strftime('%B')\n",
                "    monthly_avg = valid_stats.groupby('month')['on_time_pct'].mean()\n",
                "    \n",
                "    month_order = ['January', 'February', 'March', 'April', 'May', 'June',\n",
                "                   'July', 'August', 'September', 'October', 'November', 'December']\n",
                "    monthly_avg = monthly_avg.reindex([m for m in month_order if m in monthly_avg.index])\n",
                "    \n",
                "    print(\"\\n📅 By Month:\")\n",
                "    print(\"-\" * 40)\n",
                "    for month, pct in monthly_avg.items():\n",
                "        bar = \"█\" * int(pct // 5) + \"░\" * (20 - int(pct // 5))\n",
                "        emoji = \"🟢\" if pct >= 80 else \"🟡\" if pct >= 60 else \"🔴\"\n",
                "        print(f\"{emoji} {month:10} {pct:5.1f}% |{bar}|\")\n",
                "\n",
                "display_summary_stats(daily_stats)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Save Heatmap"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "if fig:\n",
                "    os.makedirs(os.path.join(project_root, 'static', 'plots'), exist_ok=True)\n",
                "    output_path = os.path.join(project_root, 'static', 'plots', 'on_time_heatmap_2025.html')\n",
                "    fig.write_html(output_path, include_plotlyjs='cdn')\n",
                "    print(f\"✅ Saved to: {output_path}\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.12.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Write the notebook
output_path = os.path.join(os.path.dirname(__file__), 'on_time_heatmap.ipynb')
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=4)

print(f"✅ Created notebook: {output_path}")
print("\nYou can now open and run the notebook in VS Code or Jupyter.")
